export interface CalendarDay {
  day: number;
  display: string;
  message: string;
  imagePath: string;
}

export const CALENDAR_DAYS: CalendarDay[] = [
  { day: 1, display: '1', message: 'Happy December bunbun! Here is a lil gift for you, your own advent calendar! I hope you enjoy it!', imagePath: 'assets/images/day-1.jpg' },
  { day: 2, display: '2', message: 'Your arms like a garland, your eyes like a star \n My dear, hold me closely and brighten my heart! ', imagePath: 'assets/images/day-2.jpg' },
  { day: 3, display: '3', message: 'From Europe to Asia, from Asia to Europe, \n Summer or Winter, our side-quests are plural \n You\'re bright like the day, and you\'re shining like night \n Each instant with you is a lasting delight', imagePath: 'assets/images/day-3.jpg' },
  { day: 4, display: '4', message: 'I took your gaze and embraced it, \n Your face in my face. Did \n A moth try to love a street lamp? \n The blaze felt amazing \n It coddled, embraced me \n The radiance welcomed the knight \n Shaw!', imagePath: 'assets/images/day-4.jpg' },
  { day: 5, display: '5', message: 'Some tea for the tea pet, some tea for my bunny \n The custom\'s antique but the gesture is homely \n A peak through the mirror, I\'m shy so don\'t scold me \n My love did lay dormant, hibernated coldly \n But then winter left and spring crawled in slowly \n And summer confirmed that you\'re my one and only!', imagePath: 'assets/images/day-5.jpg' },
  { day: 6, display: '6', message: 'You stole a kiss from me and left just the lipstick \n A glimpse of the passion, its shadow screams "Miss me!" \n Its specter still wails in the walls of the airport \n So I will dispell the ill will that it harbors \n I left a few times, through the sky, through the land \n But always returned \'cause I\'m a boomerang! \n I promise I\'ll be back, I\'ll fuse to your hand \n And spin you around and kiss you again', imagePath: 'assets/images/day-6.jpg' },
  { day: 7, display: '7', message: 'Two lovedoves went hiding in Broek in Waterland \n Sheep, fields, canals, and a barge at the other end \n Night walk and sunrise, nothing felt amiss \n A warm bath, a big bed, a horse in the mist', imagePath: 'assets/images/day-7.jpg' },
  { day: 8, display: '8', message: 'The plaza is empty, so let\'s take a selfie \n Pretty blue coat and my sweater in mandarin\n Let\'s juxtapose both supporting and bantering \n I opened the door to my heart so please enter in \n Act like you\'re home, leave your things all around the place \n They\'ll keep me going when my thoughts will interlace \n Intimate kisses will mix with hand-holding \n You are my missus, my one and my only', imagePath: 'assets/images/day-8.jpg' },
  { day: 9, display: '9', message: 'Come be my partner for this life-long ball \n There will be flowers and kisses for all \n Give me a bow, and a twirl, and a dance \n I\'ll lift you up - the whole world in my hands', imagePath: 'assets/images/day-10.jpg' },
  { day: 10, display: '10', message: 'You biked while I ran, united in freeing \n Ourselves from the curse labeled time \n The lamp posts were bright, but I couldn\'t see them \n Your big eyes left me paralyzed \n Medusa, my best friend, please take this Ambrosia \n Oh Zeus, why did your lighting strike? \n Aphrodite\'s sons: one wields bow, one wields phobia \n Only one of them led me right', imagePath: 'assets/images/day-9.jpg' },
  { day: 11, display: '11', message: 'Eyes shining like night rain reflecting the neons \n Or stars meticulously plucked from the sky \n Eurydice let me free you from your demons \n No evil will reach you, your ears won\'t hear lies \n Take refuge in my arms, I\'ll be your oasis \n Porco Rosso\'s cove opens on a clear sky \n Let my furnace warm you, don\'t fear it, embrace it \n And never let sparks disappear from your eyes', imagePath: 'assets/images/day-11.jpg' },
  { day: 12, display: '12', message: 'My kisskisswifewife I love you beyond measures \n Please let my blue hoodie save you from frostbite \n Every day with you I discover new treasures \n Like the Prinsentuin park that was hidden from sight', imagePath: 'assets/images/day-12.jpg' },
  { day: 13, display: '13', message: 'It truly was homely to visit Ikea \n To wander, to lose ourselves to the idea \n Of living in one house, not split by a screen \n Two hands to unite us, two hands for ice cream', imagePath: 'assets/images/day-13.jpg' },
  { day: 14, display: '14', message: 'I blink my eyes, already been a year \n A year of laughs, our future\'s pioneer \n Who could\'ve known the red thread would prevail \n The skies would brighten up, the sun would tell our tale \n Even the planet couldn\'t keep the two of us apart \n I flew, I flew, I flew to get close to my heart \n Our love feels ancient, pure, devoid of this modernity \n It\'s been a year, an instant that feels like eternity', imagePath: 'assets/images/day-14.jpg' },
  { day: 15, display: '15', message: 'Like the sun in July, she warms me to my bones \n She caresses my cold weathered skin \n She irradiates me with her kindness, her love \n And leaves me with a kiss on the cheek', imagePath: 'assets/images/day-15.jpg' },
  { day: 16, display: '16', message: 'On the opposite side of a church let us celebrate\nOur first christmas. Let\'s find the best gifts\nAre they required for our standards to elevate\nOr just a kiss is enough in the lift', imagePath: 'assets/images/day-16.jpg' },
  { day: 17, display: '17', message: 'A rose in the mouth call me Zoro, the masked masked thief\nI came and I stole your heart, took every piece\nBut caught in the heat, I did not realize that\nYou clutched mine so hard and you\'ll never release', imagePath: 'assets/images/day-17.jpg' },
  { day: 18, display: '18', message: 'Bestest gift giver, so thoughtful, so artsy\nThank you for loving me even in dreams\nThings that I love about you, plenty like shark teeth\nAnd kisses way softer than hands when you sleep', imagePath: 'assets/images/day-18.jpg' },
  { day: 19, display: '19', message: 'Fresh rain made shiny the floors of the convent\nAnd holiday lights were reflected within\nBut none of them could rivalize those on your end\nFor your smiling eyes made my future written', imagePath: 'assets/images/day-19.jpg' },
  { day: 20, display: '20', message: 'One mommy, one daddy, and one little fulwul\nAll three are in green, what a sweet family\nThey cherish each other and they kiss so often\nThat even the clouds smile at them hapily', imagePath: 'assets/images/day-20.jpg' },
  { day: 21, display: '21', message: 'There were many mirrors and all of them gorgeous\nSince they all reflected the love of my life\nAs long as she\'s here I won\'t need malls like Orchard\nFor all that I need can be found in my wife', imagePath: 'assets/images/day-21.jpg' },
  { day: 22, display: '22', message: 'True love is more present at airports than weddings\nSo come to this booth, let me immortalize\nOur smile and our hearts and our kisses in paintings\nFor every pic with you is a work of art', imagePath: 'assets/images/day-22.jpg' },
  { day: 23, display: '23', message: 'To find a girl like you is like to find a unicorn\n You are so kind that you radiate a kind of unique glow \n Between an angel and you I won\'t find a difference\nYou are my rose and I\'m your little prince\n', imagePath: 'assets/images/day-23.jpg' },
  { day: 24, display: '24', message: 'I came and I left quick like the morning breeze\nA spark in the cover of old canopies\nPlease breathe in, embrace this short moment of peace\nA respise from chaos, a kiss in the mist', imagePath: 'assets/images/day-24.jpg' },
  { day: 25, display: '25', message: 'It\'s our second Christmas, and there shall be more\nMore pretty New Year trees and good gifts galore\nSo loe and behold how our story\'ll unfold\nAnd let me lead you to the ends of the world mi amor', imagePath: 'assets/images/day-25.jpg' },
  { day: 26, display: '26', message: 'Not even centuries with you would be enough for me\nThe skies could fall, the sun could burn, the seas could dry wholly \nThe ground could turn eternal white, or dry entirely \nBut you\'ll still be stuck in my heart, my brain, and all my dreams', imagePath: 'assets/images/day-26.jpg' },
  { day: 27, display: '27', message: 'Let\'s ride together to the sunset\nYour hand in mine, where it belongs\nTake flight, the night skies hold all answers\nFor in your eyes they sing their song\nThe moon will conduct this grand concert\nAnd every star will harmonize\nThe song will soothe you, like an onsen\nGive you a glimpse of paradise', imagePath: 'assets/images/day-27.jpg' },
  { day: 28, display: '28', message: 'My arm is resting on your shoulders, my unconditional supports\n A canopy to shield your worries, you\'ll be protected from the ghosts\nYou\'ll never have to see their ire, their wrath will never reach your soul\n So rest your weary eyes, so tired, come hide in my chest it\'s all yours\n', imagePath: 'assets/images/day-28.jpg' },
  { day: 29, display: '3 days to New Year!', message: 'Big wife is huge like big man Blastoise\nBug wife is looking up to me\nHuge eyes, small face, you make me wonder\nWill kids be copies? Hopefully', imagePath: 'assets/images/day-29.jpg' },
  { day: 30, display: '2 days to New Year!', message: 'In the darkness of space, my ship navigates slowly\nFrom planet to planet in search of my rose\nYour smile, my sole beacon, it radiates, glows free\nAs long as it\'s there, I\'ll know where is my home\nSo many encounters, so easy to get lost\nNot know who you are and forget the way back\nBut as long as your smile will shine every morning\nMy path will be set in stone, I\'m yours, that\'s a fact', imagePath: 'assets/images/day-30.jpg' },
  { day: 31, display: '1 day to New Year!', message: '2 days to New Year! 🎉', imagePath: 'assets/images/day-31.jpg' },
  { day: 32, display: 'Happy New Year!', message: 'Happy New Year! 🎉', imagePath: 'assets/images/day-32.jpg' }
];

